#!/bin/sh
#
# This script will populate a vfat formatted USB stick with the Skunkboard
# distribution files (installers and source material). It makes the following
# assumptions:
#
# 1) You have already built a distribution zip file using mkdistzip.sh
#
# 2) You have the "unzip" utility installed on the computer where you're running
#    this script.
#
# 3) You have the 'fatlabel' utility from the dosfstools project installed on
#    the computer where you're running this script
#
# 4) You can execute arbitrary commands as root using sudo.
#
# If all this is true, simply run the script as follows:
#
#   $ ./mkusb.sh \
#       <zip file generated by mkdistzip.sh> \
#       <path to USB stick's first partition device file>
#
# For example:
#
#   $ ./mkusb.sh skunkdist.zip /dev/sdb1
#
# And it should prompt you for the rest.
#
usage() {
	echo ""
	echo "usage: mkusb.sh \\"
	echo "           <zip file generated by mkdistzip.sh> \\"
	echo "           <full path to USB stick's first partition device file>"
	echo ""
	echo "example:"
	echo ""
	echo "  mkusb.sh skunkdist.zip /dev/sdb1"
	echo ""
	echo "See the comment at the top of this script for more details."
	echo ""

	exit 1
}

getpath() {
	DIR="`dirname $1`"
	RET="`cd "$DIR"; pwd`"

	echo "$RET"
}

DISTFILE="`getpath "$1"`/`basename "$1"`"
DEVFILE="$2"

if [ ! -r "$DISTFILE" -o ! -f "$DISTFILE" ]; then
	echo "Skunkboard distribution zip file not found"
	usage
else
	echo "Using Skunkboard distribution zip file: '$DISTFILE'"
fi

if [ ! -b "$DEVFILE" ]; then
	echo "USB stick first partition device file not found"
	usage
else
	echo "Using USB stick first partition device file: '$DEVFILE'"
fi

mount | grep "$DEVFILE" > /dev/null
if [ $? -eq 0 ]; then
	echo "USB stick is mounted. Please unmount it first"
	exit 1
fi

DEVLABEL="`sudo fatlabel "$DEVFILE"|tail -n 1`"

echo "USB Device partition '$DEVFILE' has label '$DEVLABEL'"
echo "*** THIS SCRIPT WILL WIPE ALL DATA ON THE ABOVE DEVICE! ***"
echo -n "Type 'yes' to continue: "
read YESNO
if [ "x$YESNO" != "xyes" ]; then
	exit 1
fi

sudo fatlabel "$DEVFILE" SKUNKBOARD
MNTDIR="`mktemp -d`"
sudo mount -o uid=`id -u`,gid=`id -g` "$DEVFILE" "$MNTDIR"
cd "$MNTDIR"
rm -rf *
rm -rf .*
unzip "$DISTFILE"
cd
sudo umount "$MNTDIR"
rm -rf "$MNTDIR"

# Seems to work even on partitions rather than just the actual disk, but...
# still seems a little sketchy.
sudo eject "$DEVFILE"

echo "All done! It is now safe to unplug your USB stick. Please do so."
